/**
 * SECURITY NOTE (M3): This function is invoked by Supabase Auth as a hook, not
 * by public callers. Supabase does not yet support SUPABASE_AUTH_HOOK_SECRET for
 * custom SMS hooks (only for Postgres hooks). The effective mitigations in place are:
 *  1. The function is only reachable within the Supabase project network context.
 *  2. An invitation gate blocks OTP dispatch for unknown numbers.
 *  3. Country-code allowlist restricts to Singapore (+65) numbers.
 * If Supabase adds hook-secret support, validate Authorization here at that time.
 */
import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { AwsClient } from 'https://esm.sh/aws4fetch@1.0.19';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

function maskPhone(phone: string): string {
    if (phone.length < 7) return '***';
    return phone.slice(0, 3) + '****' + phone.slice(-4);
}

function requireEnv(key: string): string {
    const val = Deno.env.get(key);
    if (!val) throw new Error(`Missing required env var: ${key}`);
    return val;
}

// Supabase Auth (GoTrue) expects hook errors in this envelope shape. Returning a
// bare { error: 'some string' } makes GoTrue fail to parse the response and surface
// the opaque "invalid payload is sent to hook" message to the client instead of the
// real `message` below.
function hookError(httpCode: number, message: string): Response {
    return new Response(JSON.stringify({ error: { http_code: httpCode, message } }), {
        status: httpCode,
        headers: { 'Content-Type': 'application/json' },
    });
}

// Uses SNS-scoped IAM user (lyfe-sns-sms), separate from AWS_* which is used by
// verify-face (rekognition). Kept distinct so a rotation on one does not break the other.
const aws = new AwsClient({
    accessKeyId: requireEnv('SNS_AWS_ACCESS_KEY_ID'),
    secretAccessKey: requireEnv('SNS_AWS_SECRET_ACCESS_KEY'),
    region: 'ap-southeast-1',
    service: 'sns',
});

// Phone numbers that skip SMS sending (OTP still generated by Supabase Auth).
// Set OTP_WHITELIST_PHONES as a comma-separated env var, e.g. "+6580000001,+6580000002"
const WHITELIST = (Deno.env.get('OTP_WHITELIST_PHONES') || '').split(',').filter(Boolean);

// Basic E.164 format: + followed by 8-15 digits
const PHONE_RE = /^\+\d{8,15}$/;

serve(async (req) => {
    const payload = await req.json();
    const phone = '+' + payload.sms.phone;
    const otp = payload.sms.otp;

    // ── Input validation ───────────────────────────────────────
    if (!PHONE_RE.test(phone)) {
        console.error(`[custom-sms-hook] Invalid phone format: ${maskPhone(phone)}`);
        return hookError(400, 'Invalid phone number format');
    }

    // ── Whitelist check — skip SMS, OTP still works ────────────
    if (WHITELIST.includes(phone)) {
        console.log(`[custom-sms-hook] Skipping SMS for whitelisted number`);
        return new Response(JSON.stringify({}), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
        });
    }

    // ── Country code allowlist — Singapore only ─────────────────
    if (!phone.startsWith('+65')) {
        console.log(`[custom-sms-hook] Blocked non-SG number: ${maskPhone(phone)}`);
        return hookError(400, 'Unsupported country code');
    }

    // ── Invitation gate — block OTP for uninvited numbers ──────
    // Allow existing users (returning login) and invited numbers.
    // Phone formats: hook receives with '+', DB may store with or without '+'.
    // NOTE: a phone can legitimately match more than one row (e.g. a stray/test
    // record that shares a number), so we use .limit(1) rather than .maybeSingle()
    // — the latter ERRORS on multiple matches, which would wrongly block a real
    // user whose number happens to be duplicated elsewhere in the table.
    const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
    const phoneNoPlus = phone.replace(/^\+/, '');

    const { data: existingUsers, error: userLookupError } = await admin
        .from('users')
        .select('id')
        .in('phone', [phone, phoneNoPlus])
        .limit(1);

    if (userLookupError) {
        console.error('[custom-sms-hook] User lookup failed:', userLookupError.message);
        return hookError(500, 'Could not verify number, please try again');
    }

    if (!existingUsers || existingUsers.length === 0) {
        // Not an existing user — check for a pending invitation
        const { data: invitations, error: inviteLookupError } = await admin
            .from('member_invitations')
            .select('id')
            .in('phone', [phone, phoneNoPlus])
            .eq('status', 'pending')
            .limit(1);

        if (inviteLookupError) {
            console.error('[custom-sms-hook] Invitation lookup failed:', inviteLookupError.message);
            return hookError(500, 'Could not verify number, please try again');
        }

        if (!invitations || invitations.length === 0) {
            console.log(`[custom-sms-hook] Blocked OTP for uninvited number: ${maskPhone(phone)}`);
            return hookError(400, 'No invitation found for this number');
        }
    }

    const body = new URLSearchParams({
        Action: 'Publish',
        PhoneNumber: phone,
        Message: `Your Lyfe verification code is: ${otp}. Valid for 10 minutes. Do not share this code.`,
        'MessageAttributes.entry.1.Name': 'AWS.SNS.SMS.SMSType',
        'MessageAttributes.entry.1.Value.DataType': 'String',
        'MessageAttributes.entry.1.Value.StringValue': 'Transactional',
        'MessageAttributes.entry.2.Name': 'AWS.SNS.SMS.SenderID',
        'MessageAttributes.entry.2.Value.DataType': 'String',
        // Sender ID must EXACTLY match what is registered & whitelisted in the
        // Singapore SSIR (smsregistry.sg) — "MKTR" is Live; "LYFE" is unregistered
        // and would be relabelled "Likely-SCAM" by the SG telcos. Case-sensitive.
        'MessageAttributes.entry.2.Value.StringValue': 'MKTR',
    });

    try {
        const abortCtl = new AbortController();
        const fetchTimeout = setTimeout(() => abortCtl.abort(), 30000);
        let response: Response;
        try {
            response = await aws.fetch('https://sns.ap-southeast-1.amazonaws.com/', {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body: body.toString(),
                signal: abortCtl.signal,
            });
        } finally {
            clearTimeout(fetchTimeout);
        }

        if (!response.ok) {
            const error = await response.text();
            console.error('[custom-sms-hook] SNS error:', error);
            return hookError(400, 'SMS delivery failed');
        }

        return new Response(JSON.stringify({}), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
        });
    } catch (error) {
        console.error('[custom-sms-hook]', error);
        return hookError(500, 'Internal server error');
    }
});
