import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { AwsClient } from 'https://esm.sh/aws4fetch@1.0.19';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

function maskPhone(phone: string): string {
    if (phone.length < 7) return '***';
    return phone.slice(0, 3) + '****' + phone.slice(-4);
}

const aws = new AwsClient({
    accessKeyId: Deno.env.get('AWS_ACCESS_KEY_ID')!,
    secretAccessKey: Deno.env.get('AWS_SECRET_ACCESS_KEY')!,
    region: 'ap-southeast-1',
    service: 'sns',
});

// Phone numbers that skip SMS sending (OTP still generated by Supabase Auth).
// Set OTP_WHITELIST_PHONES as a comma-separated env var, e.g. "+6580000001,+6580000002"
const WHITELIST = (Deno.env.get('OTP_WHITELIST_PHONES') || '').split(',').filter(Boolean);

// Basic E.164 format: + followed by 8-15 digits
const PHONE_RE = /^\+\d{8,15}$/;

serve(async (req) => {
    const payload = await req.json();
    const phone = '+' + payload.sms.phone;
    const otp = payload.sms.otp;

    // ── Input validation ───────────────────────────────────────
    if (!PHONE_RE.test(phone)) {
        console.error(`[custom-sms-hook] Invalid phone format: ${maskPhone(phone)}`);
        return new Response(JSON.stringify({ error: 'Invalid phone number format' }), {
            status: 400,
            headers: { 'Content-Type': 'application/json' },
        });
    }

    // ── Whitelist check — skip SMS, OTP still works ────────────
    if (WHITELIST.includes(phone)) {
        console.log(`[custom-sms-hook] Skipping SMS for whitelisted number`);
        return new Response(JSON.stringify({}), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
        });
    }

    // ── Invitation gate — block OTP for uninvited numbers ──────
    // Allow existing users (returning login) and invited numbers
    // Phone formats: hook receives with '+', DB may store with or without '+'
    const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
    const phoneNoPlus = phone.replace(/^\+/, '');

    const { data: existingUser } = await admin
        .from('users')
        .select('id')
        .in('phone', [phone, phoneNoPlus])
        .maybeSingle();

    if (!existingUser) {
        // Not an existing user — check for a pending invitation
        const { data: invitation } = await admin
            .from('member_invitations')
            .select('id')
            .in('phone', [phone, phoneNoPlus])
            .eq('status', 'pending')
            .maybeSingle();

        if (!invitation) {
            console.log(`[custom-sms-hook] Blocked OTP for uninvited number: ${maskPhone(phone)}`);
            return new Response(JSON.stringify({ error: 'No invitation found for this number' }), {
                status: 400,
                headers: { 'Content-Type': 'application/json' },
            });
        }
    }

    const body = new URLSearchParams({
        Action: 'Publish',
        PhoneNumber: phone,
        Message: `Your Lyfe verification code is: ${otp}. Valid for 10 minutes. Do not share this code.`,
        'MessageAttributes.entry.1.Name': 'AWS.SNS.SMS.SMSType',
        'MessageAttributes.entry.1.Value.DataType': 'String',
        'MessageAttributes.entry.1.Value.StringValue': 'Transactional',
        'MessageAttributes.entry.2.Name': 'AWS.SNS.SMS.SenderID',
        'MessageAttributes.entry.2.Value.DataType': 'String',
        'MessageAttributes.entry.2.Value.StringValue': 'LYFE',
    });

    try {
        const response = await aws.fetch('https://sns.ap-southeast-1.amazonaws.com/', {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: body.toString(),
        });

        if (!response.ok) {
            const error = await response.text();
            console.error('[custom-sms-hook] SNS error:', error);
            return new Response(JSON.stringify({ error: 'SMS delivery failed' }), {
                status: 400,
                headers: { 'Content-Type': 'application/json' },
            });
        }

        return new Response(JSON.stringify({}), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
        });
    } catch (error) {
        console.error('[custom-sms-hook]', error);
        return new Response(JSON.stringify({ error: 'Internal server error' }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
        });
    }
});
