-- =====================================================================
-- DELIBERATE NO-OP (audit C3, 2026-06-12)
--
-- This version slot is recorded as applied in production's
-- supabase_migrations.schema_migrations, so the file must keep existing
-- (never rename or delete applied files) — but production NEVER executed
-- its former contents: the slot was repaired into history later, as a
-- partial schema snapshot (generated 2026-03-08) intended for
-- bootstrapping fresh environments.
--
-- That snapshot was retired because it made every fresh rebuild
-- impossible:
--   * it duplicated objects the real chain creates unguarded
--     (CREATE TYPE user_role, CREATE TABLE public.users, ... — replay died
--     at 20260228103319_create_users_and_roles.sql), and
--   * it was incomplete anyway (candidate_profiles, disc_results,
--     disc_responses, invitations, jobs, progress_signals were missing).
--
-- Fresh rebuilds now work from the real migration chain itself, starting
-- at 20260228103319_create_users_and_roles.sql, with Dashboard-created
-- objects baselined in 20260320173000_baseline_dashboard_tables.sql.
-- The retired snapshot remains available in git history.
-- =====================================================================

SELECT 1;
