-- Allow authenticated staff to read from the candidate-pdfs bucket.
-- PDFs are generated by lyfe-sg (using service-role) and need to be
-- viewable by staff on mobile (using anon key + JWT).
-- Uses jwt app_metadata to avoid recursive RLS on users table.
CREATE POLICY "Staff can read candidate PDFs"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'candidate-pdfs'
    AND (((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text) IN ('admin', 'director', 'manager', 'pa'))
  );
